import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import {  Poppins } from 'next/font/google'


const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${montserrat.className}   antialiased `}>
      <div className="flex w-10/12 mx-auto max-w-[1400px] ">
        {children}

      </div>
      </body>
    </html>
  );
}
